### ISSUE TITLE
Needs to launch an action twice to make it really works

### ISSUE THREAD

**Issue by dmndrz** [torifat/xiaomi-mi-air-purifier#111]
Hi! I created some scenarios to automatically change the fan speed when I want to (with 3 different speeds). Somehow I have to launch these scenes twice before it actually works. Same to turn the purifier on/off. I have this issue when I tap on a scenario (on all of my devices), and with Siri too.

I tap the button of a scene (including a different fan speed than the actual one) in the Home app, or ask Siri to launch a scene or turn the purifier on/off. The scene fails to launch, or Siri says that the purifier is not responding. Then I do this again a few seconds later and the purifier seems to have woken up and it works.

**Logs:**

```
[5/12/2021, 1:28:00 PM] [homebridge-xiaomi-mi-air-purifier] Characteristic 'Active': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[5/12/2021, 1:28:00 PM] [homebridge-xiaomi-mi-air-purifier] Error: 
    at Active.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1663:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/with-device.ts:30:26
[5/12/2021, 1:28:01 PM] [homebridge-xiaomi-mi-air-purifier] Characteristic 'Target Air Purifier State': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[5/12/2021, 1:28:01 PM] [homebridge-xiaomi-mi-air-purifier] Error: 
    at TargetAirPurifierState.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1663:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/with-device.ts:30:26
[5/12/2021, 1:28:01 PM] [homebridge-xiaomi-mi-air-purifier] Characteristic 'Rotation Speed': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[5/12/2021, 1:28:01 PM] [homebridge-xiaomi-mi-air-purifier] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1663:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/with-device.ts:30:26
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge ****",
        "username": "**:**:**:**:**:**",
        "port": *****,
        "pin": "***-**-***"
    },
    "accessories": [
        {
            "name": "Purificateur",
            "address": "IP",
            "token": "token",
            "enableAirQuality": true,
            "enableTemperature": true,
            "enableHumidity": true,
            "filterChangeThreshold": 1,
            "enableFanSpeedControl": true,
            "enableChildLockControl": false,
            "accessory": "XiaomiMiAirPurifier"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": ****,
            "auth": "form",
            "theme": "cyan",
            "tempUnits": "c",
            "lang": "fr",
            "platform": "config"
        }
    ]
}
```

**Screenshots:**

![IMG_7676](https://user-images.githubusercontent.com/18632343/117970809-65548100-b329-11eb-9b63-d2bd0422907c.jpg)

**Environment:**

- **Plugin Version**: v1.1.0
- **Homebridge Version**: v1.3.4
- **Node.js Version**: v14.16.1
- **NPM Version**: v7.11.2
- **Operating System**: macOS

**Comment by dawiinci** [comment]
I have the same issue. Voice command always fails at first.

It is very annoying.

**Comment by chigy110** [comment]
Same issue, started several days ago, I use the comming home feature in Apple Home to switch it on. Worked like charm for several month. But now it stays off when comming home, when you try to start it manually you have to send the command twice

**Comment by torifat** [comment]
Can you please try the new version? The old one wasn't working properly with Homebrige 1.3.

**Comment by torifat** [comment]
Please reopen if you are still having the issue.
