### ISSUE TITLE
No Support for XIAOMI Smart Air Purifier 4 Pro

### ISSUE THREAD

**Issue by NoCamping** [torifat/xiaomi-mi-air-purifier#277]
Hello, just tried to add my new  Smart Air Purifier 4 Pro Device and bring it to Homebridge.
But there is no connection, I am afraid this model is not supported.

Is it possible to bring it to run ? Can I do something ?
This is th offial MODEL Type / Code :    zhimi.airp.vb4

Thank you for your work! (Network Connection is fine and I already have the correct cloud token).

Log:
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside read handler for characteristic: device.power is not a function. See https://git.io/JtMGR for more info.
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Air Purifier State': Unhandled error thrown inside read handler for characteristic: device.power is not a function. See https://git.io/JtMGR for more info.
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Target Air Purifier State': Unhandled error thrown inside read handler for characteristic: device.mode is not a function. See https://git.io/JtMGR for more info.
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Rotation Speed': Unhandled error thrown inside read handler for characteristic: device.fanSpeed is not a function. See https://git.io/JtMGR for more info.
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Air Quality': Unhandled error thrown inside read handler for characteristic: device.pm2_5 is not a function. See https://git.io/JtMGR for more info.
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'PM2.5 Density': Unhandled error thrown inside read handler for characteristic: device.pm2_5 is not a function. See https://git.io/JtMGR for more info.
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: device.filterLifeLevel is not a function. See https://git.io/JtMGR for more info.
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: device.filterLifeLevel is not a function. See https://git.io/JtMGR for more info.
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: device.temperature is not a function. See https://git.io/JtMGR for more info.
[1/20/2022, 8:07:09 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Relative Humidity': Unhandled error thrown inside read handler for characteristic: device.rh is not a function. See https://git.io/JtMGR for more info.

**Comment by benchristian88** [comment]
I would love this also. thank you!

**Comment by yipyuklam** [comment]
I have same issue for Xiaomi Air Purifier 4

Version:

Xiaomi Mi Air Purifier
homebridge-xiaomi-mi-air-purifier v2.0.2

Configuration:

{
    "name": "空氣清新機",
    "address": "192.168.10.24",
    "token": "6c4ba2a9216b61f86badffcfbb8958f6",
    "enableAirQuality": true,
    "enableTemperature": true,
    "enableHumidity": true,
    "filterChangeThreshold": 5,
    "enableFanSpeedControl": true,
    "enableChildLockControl": false,
    "accessory": "XiaomiMiAirPurifier"
}

Error log:

[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside read handler for characteristic: device.power is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.power is not a function
    at Active.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/air-purifier/active.ts:21:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Air Purifier State': Unhandled error thrown inside read handler for characteristic: device.power is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.power is not a function
    at CurrentAirPurifierState.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/air-purifier/current-air-purifier-state.ts:26:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Target Air Purifier State': Unhandled error thrown inside read handler for characteristic: device.mode is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.mode is not a function
    at TargetAirPurifierState.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/air-purifier/target-air-purifier-state.ts:22:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Rotation Speed': Unhandled error thrown inside read handler for characteristic: device.fanSpeed is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.fanSpeed is not a function
    at RotationSpeed.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/air-purifier/rotation-speed.ts:26:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Air Quality': Unhandled error thrown inside read handler for characteristic: device.pm2_5 is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.pm2_5 is not a function
    at AirQuality.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/air-quality.ts:35:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'PM2.5 Density': Unhandled error thrown inside read handler for characteristic: device.pm2_5 is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.pm2_5 is not a function
    at PM2_5Density.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/pm2_5-density.ts:17:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: device.filterLifeLevel is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.filterLifeLevel is not a function
    at FilterLifeLevel.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/air-purifier/filter-life-level.ts:17:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: device.filterLifeLevel is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.filterLifeLevel is not a function
    at FilterChangeIndication.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/air-purifier/filter-change-indication.ts:28:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: device.temperature is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.temperature is not a function
    at CurrentTemperature.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/current-temperature.ts:19:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Relative Humidity': Unhandled error thrown inside read handler for characteristic: device.rh is not a function. See https://git.io/JtMGR for more info.
[1/30/2022, 5:17:51 PM] [homebridge-xiaomi-mi-air-purifier] TypeError: device.rh is not a function
    at CurrentRelativeHumidity.getHandler (/volume1/@appdata/homebridge/lib/node_modules/homebridge-xiaomi-mi-air-purifier/src/characteristics/current-relative-humidity.ts:17:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by jmuggler** [comment]
Same problem here.

**Comment by Rezessivo** [comment]
same here....

**Comment by chung0002000** [comment]
Same here

**Comment by developerrespig** [comment]
Same for me, waiting for an update :)

**Comment by developerrespig** [comment]
Just saw in another issue that there is another plugin which actually works for me which I would like to share with you:

https://github.com/merdok/homebridge-miot

**Comment by takenek** [comment]
Hello please try https://github.com/takenek/homebridge-xiaomi-air-purifier-modern
